### ISSUE TITLE
LDAP 不能登陆

### ISSUE THREAD

**Issue by wuguohua2012** [OneOaaS/monitor_ce#1]
安装好软件后不能登陆，后续版本请考虑支持。

**Comment by net592** [comment]
代码如果python 就好了，方便PR

**Comment by zhausong** [comment]
@net592  您好，python确实有好处  不过我们考虑部署成本问题  使用了二进制方式提供，且暂不以开源方式提供 欢迎关注 我们会继续更新

**Comment by zhausong** [comment]
已在新版本中修复
