### ISSUE TITLE
页面展示bug

### ISSUE THREAD

**Issue by xinghen** [OneOaaS/monitor_ce#3]
zabbix版本：3.0.9
系统版本：centos 6.5 x64
1、当前故障数量、当前故障设备数量数字不展示；
2、数据采集速率不变化，一直是一个数字，这数字值得怀疑(这个问题不是重点)；
3、当前故障列表中，当主机组名字较长时，无法友好的展示；
4、当前故障级别 显示 严重    xx.xx%，但是右侧故障列表确是空白页面，不显示。
![image](https://cloud.githubusercontent.com/assets/3716069/26303407/286f6a98-3f1a-11e7-964b-09c72f7b6984.png)
![image](https://cloud.githubusercontent.com/assets/3716069/26303433/394115ec-3f1a-11e7-9437-e1773791db64.png)

**Comment by zhausong** [comment]
已在新版本中修复
